# Generated by Django 5.0.6 on 2024-05-25 07:46

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoHubInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto_hub_name', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('linkedin', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('google_map', models.TextField()),
                ('working_days_schedule', models.CharField(max_length=50)),
                ('saturday_schedule', models.CharField(max_length=50)),
                ('sunday_schedule', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MotoHub information',
                'verbose_name_plural': 'MotoHub information',
                'db_table': 'moto_hub_information',
                'ordering': ['moto_hub_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='images/user_images/no_photo.jpg', null=True, upload_to='images/user_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_image', models.ImageField(blank=True, default='images/no_photo.jpg', null=True, upload_to='images/motorcycle_brand_images/')),
                ('moto_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_brands_info', to='application.motohubinformation')),
            ],
            options={
                'verbose_name': 'Motorcycle brands',
                'verbose_name_plural': 'Motorcycle brands',
                'db_table': 'motorcycle_brands',
                'ordering': ['brand_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_model', models.CharField(max_length=20)),
                ('motorcycle_image', models.ImageField(blank=True, null=True, upload_to='images/motorcycle_images/')),
                ('model_years_of_production', models.CharField(max_length=20)),
                ('engine_capacity', models.CharField(max_length=10)),
                ('engine_type', models.CharField(max_length=70)),
                ('engine_hp', models.CharField(max_length=10)),
                ('cooling_system_type', models.CharField(max_length=15)),
                ('number_of_gears', models.IntegerField()),
                ('fuel_tank_capacity', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('motorcycle_description', models.TextField()),
                ('motorcycle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles_info', to='application.motorcyclebrands')),
            ],
            options={
                'verbose_name': 'Motorcycles',
                'verbose_name_plural': 'Motorcycles',
                'db_table': 'motorcycles',
                'ordering': ['motorcycle_brand', 'motorcycle_model'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FavoriteMotorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.motorcycles')),
            ],
            options={
                'verbose_name': 'Favorite motorcycles',
                'verbose_name_plural': 'Favorite motorcycles',
                'db_table': 'favorite_motorcycles',
                'ordering': ['user', 'motorcycle'],
                'managed': True,
            },
        ),
    ]
